[lockscreen]
enabled = true
allow_empty_password = false
blur_intensity = 0.55
blurred_desktop = true
fingerprint = true
tint_intensity = 0.3
wallpaper = "/home/shubhattin/.config/backgrounds/shaded.png"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
  "lockscreen-clock@eDP-1",
  "lockscreen-login-box@eDP-1",
  "lockscreen-clock@DP-1",
  "lockscreen-login-box@DP-1",
]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = false

[lockscreen_widgets.widget."lockscreen-clock@eDP-1"]
enabled = true
output = "eDP-1"
type = "clock"
cx = 768.0
cy = 360.0
rotation = 0.0

[lockscreen_widgets.widget."lockscreen-clock@eDP-1".settings]
format = "{:%H:%M}\n{:%A, %d %B %Y}"

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
enabled = true
output = "eDP-1"
type = "login_box"
box_width = 400.0
box_height = 70.0
cx = 768.0
cy = 745.0
rotation = 0.0

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_password_hint = true

[lockscreen_widgets.widget."lockscreen-clock@DP-1"]
enabled = true
output = "DP-1"
type = "clock"
cx = 960.0
cy = 420.0
rotation = 0.0

[lockscreen_widgets.widget."lockscreen-clock@DP-1".settings]
format = "{:%H:%M}\n{:%A, %d %B %Y}"

[lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
enabled = true
output = "DP-1"
type = "login_box"
box_width = 400.0
box_height = 70.0
cx = 960.0
cy = 961.0
rotation = 0.0

[lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_password_hint = true
