[shell]
font_family = "JetBrainsMono Nerd Font"
corner_radius_scale = 1.0
button_borders = true
clipboard_enabled = true
clipboard_auto_paste = "auto"
clipboard_confirm_clear_history = true
clipboard_history_max_entries = 100
setup_wizard_enabled = false
settings_show_advanced = true
middle_click_opens_widget_settings = true
polkit_agent = false
telemetry_enabled = false
time_format = "{:%H:%M}"
date_format = "%A, %d %B %Y"
avatar_path = "~/.face"

[shell.animation]
enabled = true
speed = 1.0

[shell.shadow]
alpha = 0.55
direction = "down"

[shell.panel]
borders = true
shadow = true
transparency_mode = "solid"
launcher_placement = "floating"
launcher_position = "center"
clipboard_placement = "floating"
clipboard_position = "center"
control_center_placement = "attached"
control_center_position = "auto"
session_placement = "attached"
session_position = "auto"
wallpaper_placement = "attached"
wallpaper_position = "auto"
polkit_placement = "floating"
polkit_position = "center"
floating_offset = 8

[shell.launcher]
app_grid = false
categories = true
compact = false
show_icons = true
sort_by_usage = true
provider_prefix = "/"

[shell.session]
grid = false
grid_columns = 3

[[shell.session.actions]]
action = "lock"
enabled = true
shortcut = "1"

[[shell.session.actions]]
action = "logout"
enabled = true
shortcut = "2"
command = "bash ~/.config/hypr/safe-exit.sh"

[[shell.session.actions]]
action = "lock_and_suspend"
enabled = true
shortcut = "3"

[[shell.session.actions]]
action = "reboot"
enabled = true
shortcut = "4"

[[shell.session.actions]]
action = "shutdown"
enabled = true
shortcut = "5"
variant = "destructive"

[shell.screenshot]
confirm_region = false
copy_to_clipboard = true
directory = "/home/shubhattin/Pictures/Screenshots"
freeze_screen = true
save_to_file = true

[osd]
position = "top_center"
position_vertical = "top_center"
orientation = "horizontal"
scale = 1.0
background_opacity = 0.97
offset_x = 20
offset_y = 8

[osd.kinds]
volume = true
volume_output = true
volume_input = true
brightness = true
wifi = true
bluetooth = true
power_profile = true
caffeine = true
nightlight = true
dnd = true
lock_keys = true
keyboard_layout = true
privacy = true
media = true

[control_center]
sidebar = "compact"
sidebar_section = "compact"
width = 700

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"
